# Backend build
FROM alpine:latest
RUN apk add --no-cache \
  py3-django \
  py3-django-cors-headers \
  py3-django-rest-framework \
  py3-psycopg2 \
  && rm -rf /var/cache/apk/*

WORKDIR /jugaripunt
COPY ./backend /jugaripunt
RUN python manage.py collectstatic --noinput
EXPOSE ${PORT:-8000}
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:${PORT:-8000}"]