# Generated by Django 5.1.1 on 2024-11-07 12:53

import django.db.models.deletion # type: ignore
from django.db import migrations, models # type: ignore

class Migration(migrations.Migration):

    dependencies = [
        ('jugaripunt', '0003_jugador_admin_jugador_num_federat_lliga_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lliga',
            name='usuariAdmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugaripunt.jugador'),
        ),
    ]
