# Generated by Django 5.1.1 on 2024-11-07 13:04

from django.db import migrations, models # type: ignore

class Migration(migrations.Migration):

    dependencies = [
        ('jugaripunt', '0004_alter_lliga_usuariadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lliga',
            name='tipusTorneig',
            field=models.CharField(choices=[('Lliga', 'Lliga'), ('TorneigEliminatori', 'TorneigEliminatori')], default='Lliga', max_length=20),
        ),
    ]
