# Generated by Django 4.2.16 on 2024-11-24 20:41

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('jugaripunt', '0005_alter_lliga_tipustorneig'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='puntuacio',
            field=models.FloatField(default=0.0),
        ),
    ]