# Generated by Django 5.1.1 on 2024-11-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugaripunt', '0006_jugador_puntuacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='puntuacioLliga',
            field=models.IntegerField(default=0),
        ),
    ]
