# Generated by Django 5.1.1 on 2024-11-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugaripunt', '0007_jugador_puntuaciolliga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='puntuacio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lliga',
            name='resultat',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
